name: Run Jupyter Notebook - Iris Flower Classification

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch

jobs:
  run-notebook:
    runs-on: ubuntu-latest  # You can use other runners like macos-latest or windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # This will checkout your repository code

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Specify the version of Python you are using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip  # Upgrade pip
        pip install jupyter pandas scikit-learn matplotlib seaborn  # Install necessary libraries

    - name: Run Jupyter notebook - Iris Flower Classification
      run: |
        jupyter nbconvert --to notebook --execute Iris_Flower_Classification.ipynb --output result_notebook.ipynb
        # This will run the notebook and save the results as a new notebook (result_notebook.ipynb)

    - name: Upload results as artifact
      uses: actions/upload-artifact@v2
      with:
        name: result-notebook
        path: result_notebook.ipynb
        # This will upload the result notebook for you to download later
